export const QA_JOB_ID = "00000000-0000-4000-8000-000000000001";

export function evidenceBankFixture() {
  return [
    {
      id: "chinasoft_reconciliation",
      kind: "experience" as const,
      label: "Chinasoft — data reconciliation",
      text: "Built reusable SQL checks to reconcile customer records across UAT and production on IBM i / AS400.",
      tags: ["SQL", "data quality", "AS400", "UAT"],
      status: "verified" as const,
      locked: true,
      content_hash: "qa-chinasoft",
      notes: "Commercial experience — wording verified",
    },
    {
      id: "tianyuan_alert_triage",
      kind: "experience" as const,
      label: "Tianyuan — alert triage automation",
      text: "Automated database alert triage with Python and SQL utilities, reducing MTTR from about two hours to under 45 minutes.",
      tags: ["Python", "SQL", "automation", "Linux"],
      status: "verified" as const,
      locked: true,
      content_hash: "qa-tianyuan",
      notes: null,
    },
    {
      id: "movement_python_workflow",
      kind: "project" as const,
      label: "UC — movement data workflow",
      text: "Developed a reproducible Python workflow for cleaning, transforming and validating movement data.",
      tags: ["Python", "ETL", "data validation"],
      status: "draft" as const,
      locked: false,
      content_hash: "qa-movement",
      notes: "Confirm dataset scale before verification",
    },
    {
      id: "legacy_accuracy_metric",
      kind: "experience" as const,
      label: "Legacy accuracy metric",
      text: "Improved data accuracy by approximately 20%.",
      tags: ["metric", "data quality"],
      status: "needs_review" as const,
      locked: false,
      content_hash: "qa-metric",
      notes: "Replace with a measurable mismatch rate or omit",
    },
  ];
}

const checks = [
  "Evidence-grounded claims",
  "No repeated work/projects",
  "Evidence-backed skills",
  "Metric confidence",
  "Resume page layout",
  "Cover letter page layout",
  "Resume-cover letter alignment",
  "Complementary cover letter",
  "Contact and work rights",
  "Dates and timeline",
  "Locked evidence integrity",
].map((label, index) => ({
  id: `qa-${index + 1}`,
  label,
  status: index === 3 ? "warning" : "pass",
  detail: index === 3 ? "Four unverified metrics were omitted" : "Validation passed",
}));

export function dashboardFixture() {
  const now = new Date().toISOString();
  const jobs = [
    {
      id: QA_JOB_ID,
      company: "Example Data Platform",
      title: "Data Engineer",
      location: "Christchurch, Canterbury",
      overall_score: 86,
      recommendation: "apply",
      discovered_at: now,
      source_url: "https://www.linkedin.com/jobs/view/4123456789",
      ingestion_mode: "automatic",
      source_category: "job_alert",
      platform: "linkedin",
      opportunity_kind: "job",
      status: "documents_ready",
    },
    {
      id: "00000000-0000-4000-8000-000000000002",
      company: "Canterbury Systems",
      title: "Analytics Engineer",
      location: "Christchurch, Canterbury",
      overall_score: 74,
      recommendation: "consider",
      discovered_at: now,
      source_url: "https://www.trademe.co.nz/a/jobs/it/listing/5123456789",
      ingestion_mode: "manual",
      source_category: "manual_url",
      platform: "trademe",
      opportunity_kind: "job",
      status: "analyzed",
    },
    {
      id: "00000000-0000-4000-8000-000000000003",
      company: "LinkedIn",
      title: "Data recruiter conversation",
      location: null,
      overall_score: null,
      recommendation: null,
      discovered_at: now,
      source_url: "https://www.linkedin.com/in/example-recruiter",
      ingestion_mode: "manual",
      source_category: "recruiter",
      platform: "linkedin",
      opportunity_kind: "recruiter",
      status: "discovered",
    },
  ];
  return {
    jobs,
    stats: { jobs: 3, averageMatch: 80, apply: 1, consider: 1, low: 0, skip: 0, archived: 0, newToday: 3 },
  };
}

export function jobFixture(id: string) {
  if (id !== QA_JOB_ID) return null;
  return {
    id,
    company: "Example Data Platform",
    title: "Data Engineer",
    location: "Christchurch, Canterbury",
    source_url: "https://www.linkedin.com/jobs/view/4123456789",
    employment_type: "Full time",
    salary_text: "$95,000–$115,000",
    jd_clean: "Build reliable Python and SQL data pipelines. Maintain data quality and work with stakeholders.",
    requirements: { required_skills: ["Python", "SQL", "ETL", "data quality"] },
    discovered_at: new Date().toISOString(),
    platform: "linkedin",
    opportunity_kind: "job",
    overall_score: 86,
    technical_score: 90,
    experience_score: 80,
    education_score: 95,
    domain_score: 80,
    seniority_score: 78,
    location_score: 100,
    work_rights_score: 100,
    recommendation: "apply",
    matched_evidence: ["Python", "SQL", "data quality"],
    partial_evidence: ["ETL"],
    gaps: ["Azure"],
    explanation: "Strong evidence across SQL, Python, database operations and applied data study.",
    status: "documents_ready",
    applied_at: null,
    resume_path: "/generated/example/resume.pdf",
    cover_letter_path: "/generated/example/cover-letter.pdf",
    generated_at: new Date().toISOString(),
    salary_estimate_min: 95000,
    salary_estimate_max: 115000,
    salary_recommended_ask: 105000,
    salary_currency: "NZD",
    salary_period: "year",
    salary_confidence: "medium",
    salary_comparable_count: 4,
    salary_rationale: "Comparable Christchurch and remote data-engineering listings support this range.",
    salary_evidence: [],
    packet_status: "ready_to_apply",
    packet_target_profile: { target_title: "Data Engineer", positioning: ["Python", "SQL", "ETL"], evidence_selection_mode: "auto" },
    packet_requirement_map: [
      { requirement: "Python", priority: "critical", status: "matched", evidence_ids: ["tianyuan_alert_triage"] },
      { requirement: "SQL", priority: "critical", status: "matched", evidence_ids: ["chinasoft_reconciliation"] },
      { requirement: "ETL", priority: "high", status: "partial", evidence_ids: ["movement_python_workflow"] },
      { requirement: "Azure", priority: "medium", status: "gap", evidence_ids: [] },
    ],
    packet_cover_letter_mapping: [
      { paragraph: 1, purpose: "motivation", evidence_ids: ["summary:0"], job_requirements: ["data engineering"] },
      { paragraph: 2, purpose: "evidence", evidence_ids: ["chinasoft_reconciliation"], job_requirements: ["SQL"] },
      { paragraph: 3, purpose: "evidence", evidence_ids: ["tianyuan_alert_triage"], job_requirements: ["Python"] },
      { paragraph: 4, purpose: "closing", evidence_ids: ["summary:1"], job_requirements: [] },
    ],
    packet_qa_report: { ready: true, evidence_coverage: 88, resume_cover_alignment: 96, checks },
  };
}
